## For students: change this path to the root of your code
CODEROOT = ..

#CC = gcc
CC = g++ 

#CPPFLAGS = -Wall -I$(CODEROOT) -O3  # maximal optimization
CPPFLAGS = -std=c++0x -Wall -I$(CODEROOT) -g     # with debugging info
